# Generated by Django 5.2.3 on 2025-06-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Cancelled', 'Cancelled'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Placed', max_length=20),
        ),
    ]
